name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is https://github.com/Duikmeester/AL-Go-PTE@hosted)
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: read

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [self-hosted]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: Duikmeester/AL-Go-Actions/WorkflowInitialize@hosted
        with:
          eventId: 'DO0098'

  Update:
    runs-on: [self-hosted]
    needs: [Initialization]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: Duikmeester/AL-Go-Actions/ReadSettings@hosted
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl

      - name: Read secrets
        uses: Duikmeester/AL-Go-Actions/ReadSecrets@hosted
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Override TemplateUrl
        run: |
          $templateUrl = '${{ github.event.inputs.templateUrl }}'
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateUrl=$templateUrl"
          }

      - name: Calculate DirectCommit
        run: |
          $directCommit = '${{ github.event.inputs.directCommit }}'
          Write-Host '${{ github.event_name }}'
          if ('${{ github.event_name }}' -eq 'schedule') {
            Write-Host "Running Update AL-Go System Files on a schedule. Setting DirectCommit = Y"
            $directCommit = 'Y'
          }
          Add-Content -Path $env:GITHUB_ENV -Value "DirectCommit=$directCommit"

      - name: Update AL-Go system files
        uses: Duikmeester/AL-Go-Actions/CheckForUpdates@hosted
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          token: ${{ env.ghTokenWorkflow }}
          Update: Y
          templateUrl: ${{ env.TemplateUrl }}
          directCommit: ${{ env.directCommit }}

  PostProcess:
    if: always()
    runs-on: [self-hosted]
    needs: [Initialization, Update]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: Duikmeester/AL-Go-Actions/WorkflowPostProcess@hosted
        with:
          eventId: 'DO0098'
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
